apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpe-rides
  namespace: helpe
spec:
  selector:
    matchLabels:
      app: helpe-rides
  template:
    metadata:
      labels:
        app: helpe-rides
    spec:
      containers:
      - name: helpe-rides
        image: 905418446812.dkr.ecr.il-central-1.amazonaws.com/helpe-stage/helpe-rides
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "80"

---
apiVersion: v1
kind: Service
metadata:
  namespace: helpe
  name: helpe-rides-svc
spec:
  selector:
    app: helpe-rides
  type: ClusterIP
  ports:
    - port: 9009
      targetPort: 80
